//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaDestination.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AreaDestination.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code already exists and cannot be added..
        /// </summary>
        internal static string msgAreaCodeAlreadyExists {
            get {
                return ResourceManager.GetString("msgAreaCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code already exists and cannot be added {0}, {1} --&gt; {2}..
        /// </summary>
        internal static string msgAreaCodeAlreadyExistsFormatted {
            get {
                return ResourceManager.GetString("msgAreaCodeAlreadyExistsFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area does not exist..
        /// </summary>
        internal static string msgAreaDoesNotExist {
            get {
                return ResourceManager.GetString("msgAreaDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value must be greater than start value..
        /// </summary>
        internal static string msgEndValueMustBeGreaterThanStart {
            get {
                return ResourceManager.GetString("msgEndValueMustBeGreaterThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid area format passed..
        /// </summary>
        internal static string msgInvalidAreaFormatPassed {
            get {
                return ResourceManager.GetString("msgInvalidAreaFormatPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range specified..
        /// </summary>
        internal static string msgInvalidRangeSpecified {
            get {
                return ResourceManager.GetString("msgInvalidRangeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non numeric range specified..
        /// </summary>
        internal static string msgNonNumericRangeSpecified {
            get {
                return ResourceManager.GetString("msgNonNumericRangeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to explicitly add ranges to a destination containing implicit areas..
        /// </summary>
        internal static string msgUnableToAddRangesToDestinationContainingImplicitAreas {
            get {
                return ResourceManager.GetString("msgUnableToAddRangesToDestinationContainingImplicitAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse &apos;{0}&apos; to an area..
        /// </summary>
        internal static string msgUnableToParseAreaStringFormatted {
            get {
                return ResourceManager.GetString("msgUnableToParseAreaStringFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment update requires that new end is greater than previous end..
        /// </summary>
        internal static string msgUpdateNewEnd {
            get {
                return ResourceManager.GetString("msgUpdateNewEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment update requires that previous start is greater than new start.
        /// </summary>
        internal static string msgUpdateNewStart {
            get {
                return ResourceManager.GetString("msgUpdateNewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values must fall within [0,1]..
        /// </summary>
        internal static string msgValuesMustFallWithin01 {
            get {
                return ResourceManager.GetString("msgValuesMustFallWithin01", resourceCulture);
            }
        }
    }
}
