//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaDestinationTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AreaDestinationTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71059	8801
        ///71064	33
        ///71066	49
        ///71070	39
        ///71074	60
        ///71085	639
        ///71086	65
        ///97528	24373
        ///97528	24378
        ///97528	24386
        ///97528	24387
        ///97847	25573
        ///83012	43810
        ///83012	43820
        ///90386	467321
        ///90386	467322
        ///90386	467355
        ///90386	467356
        ///90386	467357
        ///90386	467358
        ///90386	467359
        ///90386	46736
        ///90386	46737
        ///90386	46739
        ///95001	41772
        ///95642	25420
        ///97280	25639
        ///97330	1876210
        ///97330	1876700
        ///97330	1876707
        ///97330	1876909
        ///97330	1876919
        ///97330	1876990
        ///97330	1876995
        ///97330	1876997
        ///97330	1876999
        ///97363	4673456
        ///97404	51181
        ///97404	511 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string destA {
            get {
                return ResourceManager.GetString("destA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71059	8801
        ///71064	33
        ///71066	49
        ///71070	39
        ///71074	60
        ///71085	639
        ///71086	65
        ///83012	43810
        ///83012	43820
        ///90386	467321
        ///90386	467322
        ///90386	467355
        ///90386	467356
        ///90386	467357
        ///90386	467358
        ///90386	467359
        ///90386	46736
        ///90386	46737
        ///90386	46739
        ///97280	25639
        ///97330	1876210
        ///97330	1876700
        ///97330	1876707
        ///97330	1876909
        ///97330	1876919
        ///97330	1876990
        ///97330	1876995
        ///97330	1876997
        ///97330	1876999
        ///97363	4673456
        ///97431	1268770
        ///97431	1268771
        ///97431	1268772
        ///97431	1268773
        ///97431	1268774
        ///97431	1268775
        ///97446	230421
        ///97446	230 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string destB {
            get {
                return ResourceManager.GetString("destB", resourceCulture);
            }
        }
    }
}
